on:
  push:
    branches: [ master ]
    tags:
      - v*
env:
  PROJECT_PATH: SiviComponents.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{github.workspace}}
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore
        run: dotnet restore ${{env.PROJECT_PATH}}
      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2.3.0
      - name: Buid
        run: dotnet build ${{env.PROJECT_PATH}} --no-restore --configuration Release
      - name: 'Pack project'
        run: dotnet pack ${{env.PROJECT_PATH}} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{env.PACKAGE_OUTPUT_DIRECTORY}}
      - name: 'Put on nuget'
        run: dotnet nuget push ${{env.PACKAGE_OUTPUT_DIRECTORY}}\*.nupkg -k ${{secrets.PRINCIPAL}} -s ${{env.NUGET_SOURCE_URL}} --skip-duplicate